Traceback (most recent call last):
  File "wind_power_nnet.py", line 249, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named matplotlib.pyplot
Traceback (most recent call last):
  File "wind_power_nnet.py", line 249, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named matplotlib.pyplot
